@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTEwM2JkY2I4YTc4OGZhZjZlODU0YSIsImVtYWlsIjoiZ2lnYW1heHJheXF1YXphQGdtYWlsLmNvbSIsImlhdCI6MTc0NTk0NjM0NywiZXhwIjoxNzQ1OTUzNTQ3fQ.pG9SQsptpw9dyn64jdZUubBzkMPbeP5me6WWyWq0lDs


### Registro de usuario
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "gigamaxrayquaza@gmail.com",
  "password": "12345678"
}

###  Validación de email 
PUT http://localhost:3000/api/user/validation
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "code": "917615"
}


###  Login correcto
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "gigamaxrayquaza@gmail.com",
  "password": "12345678"
}

### ✅ Onboarding - datos personales
PUT http://localhost:3000/api/onboarding/personal
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Alejandro",
  "surname": "Ortiz",
  "nif": "12345678A"
}


### PATCH - Compañía (empresa)
PATCH http://localhost:3000/api/onboarding/company
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "isFreelance": false,
  "name": "Mi Empresa SL",
  "cif": "B98765432",
  "address": "Calle Falsa 123"
}


### PATCH - Logo de la empresa
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer {{TOKEN}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="logo"; filename="jordi.jpg"
Content-Type: image/png

< jordi.jpg
--MyBoundary--

### ✅ Obtener perfil actual
GET http://localhost:3000/api/user/me
Authorization: Bearer {{TOKEN}}
### Soft delete (status = deleted)
DELETE http://localhost:3000/api/user
Authorization: Bearer {{TOKEN}}

### Hard delete (borrado real)
DELETE http://localhost:3000/api/user?soft=false
Authorization: Bearer {{TOKEN}}

### Solicitar recuperación de contraseña
POST http://localhost:3000/api/user/forgot-password
Content-Type: application/json

{
  "email": "gigamaxrayquaza@gmail.com"
}


### Resetear contraseña (usa el código recibido)
POST http://localhost:3000/api/user/reset-password
Content-Type: application/json

{
  "email": "gigamaxrayquaza@gmail.com",
  "code": "345020",
  "newPassword": "12345678"
}

### ✅ Invitar usuario como guest
POST http://localhost:3000/api/user/invite
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "email": "nadria656@example.com"
}

### 🔐 Login del usuario invitado
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "nadria656@example.com",
  "password": "3utoxwgx"
}

### ✅ Validar código del invitado
PUT http://localhost:3000/api/user/validation
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "code": "776738"
}


### Crear cliente
POST http://localhost:3000/api/client
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "nombre": "Ferretería El Gitano69",
  "cif": "B12345678",
  "direccion": {
    "calle": "Calle del Flamenco 7",
    "ciudad": "Triana",
    "codigoPostal": "41010",
    "pais": "España"
  }
}


### Listar clientes
GET http://localhost:3000/api/client
Authorization: Bearer {{TOKEN}}
### Obtener un cliente concreto
GET http://localhost:3000/api/client/6810fbe6d1dfc9185c5ae0bd
Authorization: Bearer {{TOKEN}}


### Archivar cliente
PATCH http://localhost:3000/api/client/archive/67f7b6ae066ff839ebbc3313
Authorization: Bearer {{TOKEN}}

### Eliminar Cliente (soft)
DELETE http://localhost:3000/api/client/67f7b6ae066ff839ebbc3313
Authorization: Bearer {{TOKEN}}

### Eliminar cliente (hard)
DELETE http://localhost:3000/api/client/681106f8ca995811e9c9d6da?soft=false
Authorization: Bearer {{TOKEN}}


### Recuperar cliente archivado
PATCH http://localhost:3000/api/client/recover/67f7b6ae066ff839ebbc3313
Authorization: Bearer {{TOKEN}}


### Crear Proyecto
POST http://localhost:3000/api/project
Authorization: Bearer {{TOKEN}}
Content-Type: application/json


{
  "nombre": "Proyecto Gitano",
  "descripcion": "Proyecto para crear un simulador de gitano",
  "cliente": "68110afac04556d6ddb84ccd" 
}


### Actualizar Proyecto
PUT http://localhost:3000/api/project/67ffc960c52cdb2f29d0361b  
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "nombre": "Proyecto Gitano Mejorado",
  "descripcion": "Proyecto mejorado para crear un simulador de gitano",
  "cliente": "6810fbe6d1dfc9185c5ae0bd"
}


### Listar Proyectos
GET http://localhost:3000/api/project
Authorization: Bearer {{TOKEN}}
Content-Type: application/json


### Obtener Proyecto por ID
GET http://localhost:3000/api/project/67ffc960c52cdb2f29d0361b 
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

### Archivar un Proyecto (Soft Delete)
DELETE http://localhost:3000/api/project/67ffc960c52cdb2f29d0361b
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

### Eliminar un Proyecto (Hard Delete)
DELETE http://localhost:3000/api/project/67ffc960c52cdb2f29d0361b?soft=false  
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

### Recuperar Proyecto Archivado
PATCH http://localhost:3000/api/project/recover/67ffc960c52cdb2f29d0361b
Authorization: Bearer {{TOKEN}}
Content-Type: application/json


### Listar proyectos archivados
GET http://localhost:3000/api/project/archived
Authorization: Bearer {{TOKEN}}
Content-Type: application/json


### Crear albarán
POST http://localhost:3000/api/deliverynote
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "numero": "12HOLA1234221",
  "fecha": "2025-04-16",
  "cliente": "68110afac04556d6ddb84ccd",  
  "total": 700,
  "proyecto": "68110b0ec04556d6ddb84cd1",  
  "horas": [
    {
      "persona": "67f7b6ae066ff839ebbc3314",  
      "horasTrabajadas": 8
    }
  ],
  "materiales": [
    {
      "material": "Cemento",
      "cantidad": 50
    }
  ]
}

### Listar albaranes
GET http://localhost:3000/api/deliverynote
Authorization: Bearer {{TOKEN}}
### Obtener albarán por ID
GET http://localhost:3000/api/deliverynote/6810fbe8d1dfc9185c5ae0f5
Authorization: Bearer {{TOKEN}}

### Eliminar albarán por ID (solo si no está firmado)
DELETE http://localhost:3000/api/deliverynote/68110b19c04556d6ddb84cd5
Authorization: Bearer {{TOKEN}}

### Descargar albarán en PDF
GET http://localhost:3000/api/deliverynote/pdf/68110b55c04556d6ddb84ceb
Authorization: Bearer {{TOKEN}}


### Firmar albarán (subiendo archivo con form-data)
PATCH http://localhost:3000/api/deliverynote/firmar/68110b55c04556d6ddb84ceb
Authorization: Bearer {{TOKEN}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firma"; filename="jordi.jpg"
Content-Type: image/jpeg

< jordi.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--



### Descargar PDF desde la nube (redirige)
GET http://localhost:3000/api/deliverynote/cloud/68110b55c04556d6ddb84ceb
Authorization: Bearer {{TOKEN}}