### Registro de usuario
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "admin4@example.com",
  "password": "12345678"
}

###  Validación de email 
PUT http://localhost:3000/api/user/validation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTQzZTMxNDJhODE3MTdjZWYyZjg0OCIsImVtYWlsIjoiYWRtaW40QGV4YW1wbGUuY29tIiwiaWF0IjoxNzQzMDExMzc3LCJleHAiOjE3NDMwMTg1Nzd9.X3KCpWT8CBCXT5eCjsu4OxwMTddrt1z-ds8iWZHjy60

{
  "code": "213056"
}


###  Login correcto
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "admin4@example.com",
  "password": "12345678"
}

### ✅ Onboarding - datos personales
PUT http://localhost:3000/api/onboarding/personal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTQzZTMxNDJhODE3MTdjZWYyZjg0OCIsImVtYWlsIjoiYWRtaW40QGV4YW1wbGUuY29tIiwiaWF0IjoxNzQzMjUwMTM4LCJleHAiOjE3NDMyNTczMzh9.sUbJfH1-W2tPzxTMrORaStrRNDrx7_MKanGYQp5n3Lw

{
  "name": "Alejandro",
  "surname": "Ortiz",
  "nif": "12345678A"
}


### PATCH - Compañía (empresa)
PATCH http://localhost:3000/api/onboarding/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTQzZTMxNDJhODE3MTdjZWYyZjg0OCIsImVtYWlsIjoiYWRtaW40QGV4YW1wbGUuY29tIiwiaWF0IjoxNzQzMjUwMTM4LCJleHAiOjE3NDMyNTczMzh9.sUbJfH1-W2tPzxTMrORaStrRNDrx7_MKanGYQp5n3Lw

{
  "isFreelance": false,
  "name": "Mi Empresa SL",
  "cif": "B98765432",
  "address": "Calle Falsa 123"
}


### PATCH - Logo de la empresa
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTQzZTMxNDJhODE3MTdjZWYyZjg0OCIsImVtYWlsIjoiYWRtaW40QGV4YW1wbGUuY29tIiwiaWF0IjoxNzQzMjUyMDI4LCJleHAiOjE3NDMyNTkyMjh9.udglu4u8_fUjs3RIl39jQbuHAR2ym7aXXhUTD27E1Os
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="logo"; filename="jordi.jpg"
Content-Type: image/png

< jordi.jpg
--MyBoundary--

### ✅ Obtener perfil actual
GET http://localhost:3000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTQzZTMxNDJhODE3MTdjZWYyZjg0OCIsImVtYWlsIjoiYWRtaW40QGV4YW1wbGUuY29tIiwiaWF0IjoxNzQzMzM5OTI1LCJleHAiOjE3NDMzNDcxMjV9.xpSmxPqP170jXrSYKgkg_-QBXUfQZkjvDUT4sekilwc

### Soft delete (status = deleted)
DELETE http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTNlMDk4OTZkMTA2MTFmNjUyYTNlMyIsImVtYWlsIjoiYWRtaW4yQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQzMDEwMjgxLCJleHAiOjE3NDMwMTc0ODF9.ASD8UlPm0HBK9eLziI9BHO_xSbfAN89l2NblLmlz-6E

### Hard delete (borrado real)
DELETE http://localhost:3000/api/user?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTNlMDk4OTZkMTA2MTFmNjUyYTNlMyIsImVtYWlsIjoiYWRtaW4yQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQzMDEwMjgxLCJleHAiOjE3NDMwMTc0ODF9.ASD8UlPm0HBK9eLziI9BHO_xSbfAN89l2NblLmlz-6E


### Solicitar recuperación de contraseña
POST http://localhost:3000/api/user/forgot-password
Content-Type: application/json

{
  "email": "admin@example.com"
}


### Resetear contraseña (usa el código recibido)
POST http://localhost:3000/api/user/reset-password
Content-Type: application/json

{
  "email": "admin@example.com",
  "code": "920433",
  "newPassword": "nuevaClave124"
}